name: Daily Cache Cleanup

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  clean_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up old caches
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prefix = 'Linux-ccache-';
            const cutoff = new Date();
            cutoff.setDate(cutoff.getDate() - 2);
            
            try {
              let page = 1;
              let hasMore = true;
              
              while (hasMore) {
                const response = await github.rest.actions.getActionsCacheList({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  per_page: 100,
                  page: page
                });
                
                const caches = response.data.actions_caches;
                if (caches.length === 0) break;
                
                const oldCaches = caches.filter(cache => {
                  const createdAt = new Date(cache.created_at);
                  return cache.key.startsWith(prefix) && createdAt < cutoff;
                });
                
                for (const cache of oldCaches) {
                  await github.rest.actions.deleteActionsCacheById({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    cache_id: cache.id
                  });
                }
                page++;
              }
            } catch (error) {
              if (error.status !== 404) throw error;
            }
