name: Clear All Caches Immediately

on:
  workflow_dispatch:  # 仅手动触发

permissions:
  actions: write  # 必须拥有缓存写入权限

jobs:
  nuke-caches:
    name: Delete All Caches
    runs-on: ubuntu-latest
    steps:
      - name: Delete all cache entries
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            
            // 获取所有缓存对象
            const response = await github.rest.actions.getActionsCacheList({ 
              owner, 
              repo,
              per_page: 100
            });
            
            // 提取所有缓存的ID
            const cacheIds = response.data.actions_caches.map(cache => cache.id);
            
            // 并行删除所有缓存（快速高效）
            const deletePromises = cacheIds.map(cacheId => 
              github.rest.actions.deleteActionsCacheById({
                owner,
                repo,
                cache_id: cacheId
              })
            );
            
            // 等待所有删除操作完成
            await Promise.all(deletePromises);
            
            // 简单确认消息
            return `Deleted ${cacheIds.length} caches`;
