name: Cache Manager

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:

permissions:
  actions: write

jobs:
  manage-caches:
    runs-on: ubuntu-latest
    steps:
      - name: Count caches
        id: cache-count
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const caches = await github.paginate(
              github.rest.actions.getActionsCacheList,
              { owner, repo, per_page: 100 }
            );
            return `CacheCount=${caches.length}`;  # 返回字符串格式
          result-encoding: string

      - name: Extract cache count
        id: extract-count
        run: |
          # 从字符串中提取数字
          COUNT=$(echo "${{ steps.cache-count.outputs.result }}" | cut -d '=' -f 2)
          echo "count=$COUNT" >> $GITHUB_OUTPUT

      - name: Clear all caches if over 13
        if: ${{ steps.extract-count.outputs.count > 13 }}
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const caches = await github.paginate(
              github.rest.actions.getActionsCacheList,
              { owner, repo, per_page: 100 }
            );
            
            // 并行删除所有缓存
            await Promise.all(caches.map(cache => 
              github.rest.actions.deleteActionsCacheById({
                owner,
                repo,
                cache_id: cache.id
              })
            ));
            
            return `Cleared ${caches.length} caches`;
