name: Clear All Caches When Over Limit

on:
  schedule:
    - cron: '0 */6 * * *'  # 每 6 小时运行一次（UTC 时间）
  workflow_dispatch:        # 支持手动触发

permissions:
  actions: write

jobs:
  clear-all-caches:
    runs-on: ubuntu-latest
    steps:
      - name: Count current caches
        id: cache-counter
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const caches = await github.paginate(
              github.rest.actions.getActionsCacheList,
              { owner, repo, per_page: 100 }
            );
            return caches.length;
          result-encoding: number
        
      - name: Clear all caches if over 13
        if: ${{ steps.cache-counter.outputs.result > 13 }}
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            
            // 获取所有缓存
            const caches = await github.paginate(
              github.rest.actions.getActionsCacheList,
              { owner, repo, per_page: 100 }
            );
            
            console.log(`⚠️ Clearing ${caches.length} caches (threshold exceeded)`);
            
            // 并行删除所有缓存（加速操作）
            await Promise.all(caches.map(cache => 
              github.rest.actions.deleteActionsCacheById({
                owner,
                repo,
                cache_id: cache.id
              })
            ));
            
            console.log('✅ All caches cleared');
